### ISSUE TITLE
delphi 10.3 android cannot be used

### ISSUE THREAD

**Issue by gtyhn** [neslib/FastMath#1]
FastSinCos(rad, sin, cos)

_fast_sincos_scalar reported an exception here

**Comment by neslib** [comment]
Thanks for reporting.
Issue was caused by changes to the way Delphi links static libraries on Android (it assumes Thumb mode now instead of Arm mode).
Fixed this by creating 2 separate static libraries: one for 10.3 and one for earlier versions of Delphi.

Let me know if this solves your issue.

**Comment by gtyhn** [comment]
Thank you for your reply, I have solved it now, thank you again
