### ISSUE TITLE
line 145 wrong on Neslib.FastMath.Sse2_64.inc

### ISSUE THREAD

**Issue by wesleybobato** [neslib/FastMath#3]
Hi Erik
It looks like you need to replace

**movq** xmm0, [ARadians]
per
**movlps** xmm0, [ARadians]

Thanks. :)

**Comment by neslib** [comment]
Well spotted. Thanks!
Although technically, both movq and movlps work in this case, movlps should be used because it is designed for floating-point values. I did that in all other places, but forgot it here.
